import type { CausalGraph } from "../types";

// Full self-map of daxaur/causalist — every real file in src/ plus the
// packages it depends on. Generated by hand from the current tree. Keep
// this in sync when files move.
export const causalistSelfGraph: CausalGraph = {
  repo: "daxaur/causalist",
  rootLabel: "causalist",
  commit: "main",
  nodes: [
    // ── entry + layout ─────────────────────────────────────────────────
    { id: "layout", label: "app/layout.tsx", path: "src/app/layout.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Root layout. Injects JetBrains Mono via next/font and Fontshare <link> for Clash Display + Satoshi. Sets metadata (title, OG, applicationName)." },
    { id: "globals", label: "app/globals.css", path: "src/app/globals.css", layer: "config", language: "css", kind: "file", summary: "Tailwind v4 theme inline. Maps --font-display/--font-sans to Clash/Satoshi. Holds shadcn base tokens and Magic UI marquee/shiny-text keyframes." },
    { id: "icon", label: "app/icon.svg", path: "src/app/icon.svg", layer: "ui", language: "svg", kind: "file", summary: "Arc+Terminus favicon. Rendered at 32×32 by Next metadata route." },
    { id: "og", label: "app/opengraph-image.svg", path: "src/app/opengraph-image.svg", layer: "ui", language: "svg", kind: "file", summary: "OG card — logo mark plus wordmark for social previews." },

    // ── routes ─────────────────────────────────────────────────────────
    { id: "page", label: "app/page.tsx", path: "src/app/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Landing page. Hero with Clash Display headline, GitHub URL input with client-side validation, BentoGrid features, language marquee, Claude credit strip." },
    { id: "repo-page", label: "app/[owner]/[repo]", path: "src/app/[owner]/[repo]/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "The canonical repo URL. Server component that awaits params, checks the preview cache, and either renders <CausalGraphViewer> or <RepoAnalyzePrompt>." },
    { id: "preview-page", label: "app/preview/[slug]", path: "src/app/preview/[slug]/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Pre-rendered canned demos. generateStaticParams enumerates PREVIEWS so routes are SSG'd." },
    { id: "dashboard-page", label: "app/dashboard", path: "src/app/dashboard/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Signed-in projects list. Uses GitHub PAT to list the user's repos via Octokit." },
    { id: "settings-page", label: "app/settings", path: "src/app/settings/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "BYO keys. Anthropic API key + GitHub PAT fields with show/hide toggles. Clears localStorage on request." },

    // ── brand / logo ───────────────────────────────────────────────────
    { id: "logo", label: "<Logo>", path: "src/components/brand/logo.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Inline SVG Arc+Terminus mark. Scales to any size. Also exports <LogoWordmark>." },

    // ── landing background ─────────────────────────────────────────────
    { id: "constellation", label: "<ConstellationBackground>", path: "src/components/landing/constellation-bg.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Canvas2D constellation — drifting dots connected by proximity lines, mouse-reactive. Runs via requestAnimationFrame." },

    // ── graph viewer ───────────────────────────────────────────────────
    { id: "graph-viewer", label: "<CausalGraphViewer>", path: "src/components/graph/causal-graph-viewer.tsx", layer: "ui", language: "tsx", kind: "file", summary: "The hero component. Dynamically imports react-force-graph-3d / -2d with ssr:false. 3D/2D toggle, directional particles colored by edge kind, click-to-select." },
    { id: "node-panel", label: "<NodePanel>", path: "src/components/graph/node-panel.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Right-docked detail panel. Semantic layer pill, path, summary, metadata. Close button." },
    { id: "layer-legend", label: "<LayerLegend>", path: "src/components/graph/layer-legend.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Bottom-left legend showing which layer color means what." },
    { id: "analyze-prompt", label: "<RepoAnalyzePrompt>", path: "src/components/graph/repo-analyze-prompt.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Shown when no graph exists. Four-stage agent progress (Structure→Dependency→Semantic→Oracle). Gated on Anthropic key." },

    // ── lib: graph data model ──────────────────────────────────────────
    { id: "types", label: "graph/types.ts", path: "src/lib/graph/types.ts", layer: "data", language: "ts", kind: "file", summary: "CausalNode, CausalEdge, SemanticLayer. LAYER_COLORS + LAYER_LABELS lookup tables." },
    { id: "devicon", label: "graph/devicon.ts", path: "src/lib/graph/devicon.ts", layer: "data", language: "ts", kind: "file", summary: "Maps file extensions + framework names to devicon jsDelivr CDN URLs. Used for per-node language logos." },
    { id: "previews-index", label: "previews/index.ts", path: "src/lib/graph/previews/index.ts", layer: "data", language: "ts", kind: "file", summary: "Registry of preview templates. Exports PREVIEWS[] and previewBySlug helper." },
    { id: "preview-causalist", label: "previews/causalist.ts", path: "src/lib/graph/previews/causalist.ts", layer: "data", language: "ts", kind: "file", summary: "Self-map. This file — node 'preview-causalist' — maps itself in the graph the user is looking at." },
    { id: "preview-nextjs", label: "previews/nextjs.ts", path: "src/lib/graph/previews/nextjs.ts", layer: "data", language: "ts", kind: "file", summary: "Hand-curated slice of vercel/next.js." },
    { id: "preview-flask", label: "previews/flask.ts", path: "src/lib/graph/previews/flask.ts", layer: "data", language: "ts", kind: "file", summary: "Hand-curated map of pallets/flask." },

    // ── lib: settings + analyze ───────────────────────────────────────
    { id: "settings-store", label: "lib/settings.ts", path: "src/lib/settings.ts", layer: "data", language: "ts", kind: "file", summary: "localStorage-backed settings store. useSyncExternalStore for multi-tab reactivity." },
    { id: "utils", label: "lib/utils.ts", path: "src/lib/utils.ts", layer: "data", language: "ts", kind: "file", summary: "shadcn cn() helper. Tailwind class merging." },

    // ── config ────────────────────────────────────────────────────────
    { id: "pkg", label: "package.json", path: "package.json", layer: "config", language: "json", kind: "file", summary: "Project manifest. Declares next, react, three, anthropic SDKs." },
    { id: "tsconfig", label: "tsconfig.json", path: "tsconfig.json", layer: "config", language: "json", kind: "file", summary: "TypeScript config. @/ aliases to src/." },
    { id: "next-config", label: "next.config.ts", path: "next.config.ts", layer: "config", language: "ts", kind: "file", summary: "Next config. Silences turbopack workspace-root warning." },
    { id: "eslint", label: "eslint.config.mjs", path: "eslint.config.mjs", layer: "config", language: "js", kind: "file" },
    { id: "postcss", label: "postcss.config.mjs", path: "postcss.config.mjs", layer: "config", language: "js", kind: "file" },
    { id: "components-json", label: "components.json", path: "components.json", layer: "config", language: "json", kind: "file", summary: "shadcn config." },

    // ── shadcn + magic ui primitives ──────────────────────────────────
    { id: "ui-button", label: "ui/button.tsx", path: "src/components/ui/button.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-input", label: "ui/input.tsx", path: "src/components/ui/input.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-card", label: "ui/card.tsx", path: "src/components/ui/card.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-dialog", label: "ui/dialog.tsx", path: "src/components/ui/dialog.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-sheet", label: "ui/sheet.tsx", path: "src/components/ui/sheet.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-command", label: "ui/command.tsx", path: "src/components/ui/command.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-bento", label: "ui/bento-grid.tsx", path: "src/components/ui/bento-grid.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Magic UI BentoGrid primitives — grid of cards with hover gradients." },
    { id: "ui-beam", label: "ui/animated-beam.tsx", path: "src/components/ui/animated-beam.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Magic UI AnimatedBeam — draws a beam between two element refs. Used to render our logo motif at feature-section scale." },
    { id: "ui-marquee", label: "ui/marquee.tsx", path: "src/components/ui/marquee.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-ticker", label: "ui/number-ticker.tsx", path: "src/components/ui/number-ticker.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-terminal", label: "ui/terminal.tsx", path: "src/components/ui/terminal.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Typing-animation terminal. Shown during analyze for a 'watching Claude think' effect." },
    { id: "ui-shiny", label: "ui/animated-shiny-text.tsx", path: "src/components/ui/animated-shiny-text.tsx", layer: "ui", language: "tsx", kind: "file" },

    // ── externals ─────────────────────────────────────────────────────
    { id: "ext-next", label: "next", layer: "infra", language: "nextjs", kind: "external", summary: "Next.js 16 App Router. Turbopack dev server." },
    { id: "ext-react", label: "react 19", layer: "infra", language: "react", kind: "external" },
    { id: "ext-tailwind", label: "tailwindcss v4", layer: "infra", language: "tailwindcss", kind: "external" },
    { id: "ext-fg3d", label: "react-force-graph-3d", layer: "infra", language: "react", kind: "external", summary: "Three.js-backed 3D force-directed graph." },
    { id: "ext-fg2d", label: "react-force-graph-2d", layer: "infra", language: "react", kind: "external", summary: "Canvas2D force-directed graph." },
    { id: "ext-three", label: "three", layer: "infra", language: "js", kind: "external" },
    { id: "ext-octokit", label: "@octokit/rest", layer: "infra", language: "github", kind: "external", summary: "GitHub REST client. Used for repo listing + content fetching." },
    { id: "ext-anthropic", label: "@anthropic-ai/sdk", layer: "infra", language: "anthropic", kind: "external", summary: "Claude API client. Oracle agent calls this directly in the browser with user's key." },
    { id: "ext-agent-sdk", label: "@anthropic-ai/claude-agent-sdk", layer: "infra", language: "anthropic", kind: "external", summary: "Subagent orchestrator. Runs Structure/Dependency/Semantic/Oracle in parallel from the Node side." },
    { id: "ext-supabase", label: "@supabase/supabase-js", layer: "data", language: "postgres", kind: "external", summary: "Phase-2 graph cache. Not yet wired." },
    { id: "ext-phosphor", label: "@phosphor-icons/react", layer: "ui", language: "react", kind: "external", summary: "Icon set — duotone for emphasis, regular elsewhere." },
    { id: "ext-framer", label: "framer-motion", layer: "ui", language: "react", kind: "external" },
    { id: "ext-devicon", label: "devicon (CDN)", layer: "ui", language: "html", kind: "external", summary: "Language logos served from jsDelivr." },
    { id: "ext-fontshare", label: "Fontshare", layer: "ui", language: "css", kind: "external", summary: "Hosts Clash Display + Satoshi." },

    // ── agents (conceptual — not yet coded) ────────────────────────────
    { id: "agent-structure", label: "StructureAgent", layer: "logic", language: "anthropic", kind: "module", summary: "Walks file tree, classifies dirs, detects frameworks. System prompt: 'you classify file system nodes.'" },
    { id: "agent-dependency", label: "DependencyAgent", layer: "logic", language: "anthropic", kind: "module", summary: "Extracts import/call/data-flow edges from source via Grep." },
    { id: "agent-semantic", label: "SemanticAgent", layer: "logic", language: "anthropic", kind: "module", summary: "Writes a plain-English summary + layer class for every node." },
    { id: "agent-oracle", label: "OracleAgent", layer: "logic", language: "anthropic", kind: "module", summary: "Merges the three into a final CausalGraph. Handles 'what if?' queries with extended thinking." },

    // ── future surfaces ────────────────────────────────────────────────
    { id: "cli", label: "causalist CLI", layer: "infra", language: "ts", kind: "module", summary: "Node CLI. `causalist map <url>` → JSON → opens browser. Universal — works for any agent with shell access." },
    { id: "plugin", label: "Claude Code plugin", layer: "infra", language: "ts", kind: "module", summary: "Bundle: skill + .mcp.json + bin/causalist. One-line install into Claude Code." },
  ],
  edges: [
    // layout wiring
    { source: "layout", target: "page", kind: "imports" },
    { source: "layout", target: "globals", kind: "imports" },
    { source: "layout", target: "ext-fontshare", kind: "imports" },

    // landing
    { source: "page", target: "constellation", kind: "imports" },
    { source: "page", target: "logo", kind: "imports" },
    { source: "page", target: "ui-button", kind: "imports" },
    { source: "page", target: "ui-input", kind: "imports" },
    { source: "page", target: "ui-bento", kind: "imports" },
    { source: "page", target: "ui-beam", kind: "imports" },
    { source: "page", target: "ui-marquee", kind: "imports" },
    { source: "page", target: "ui-shiny", kind: "imports" },
    { source: "page", target: "settings-store", kind: "imports" },
    { source: "page", target: "ext-phosphor", kind: "imports" },

    // repo page
    { source: "repo-page", target: "logo", kind: "imports" },
    { source: "repo-page", target: "graph-viewer", kind: "imports" },
    { source: "repo-page", target: "analyze-prompt", kind: "imports" },
    { source: "repo-page", target: "previews-index", kind: "imports" },
    { source: "repo-page", target: "ext-phosphor", kind: "imports" },

    // preview page
    { source: "preview-page", target: "logo", kind: "imports" },
    { source: "preview-page", target: "graph-viewer", kind: "imports" },
    { source: "preview-page", target: "previews-index", kind: "imports" },

    // dashboard
    { source: "dashboard-page", target: "logo", kind: "imports" },
    { source: "dashboard-page", target: "settings-store", kind: "imports" },
    { source: "dashboard-page", target: "ext-octokit", kind: "calls" },

    // settings
    { source: "settings-page", target: "logo", kind: "imports" },
    { source: "settings-page", target: "settings-store", kind: "imports" },
    { source: "settings-page", target: "ui-button", kind: "imports" },
    { source: "settings-page", target: "ui-input", kind: "imports" },

    // graph viewer internals
    { source: "graph-viewer", target: "types", kind: "imports" },
    { source: "graph-viewer", target: "devicon", kind: "imports" },
    { source: "graph-viewer", target: "node-panel", kind: "imports" },
    { source: "graph-viewer", target: "layer-legend", kind: "imports" },
    { source: "graph-viewer", target: "ext-fg3d", kind: "imports" },
    { source: "graph-viewer", target: "ext-fg2d", kind: "imports" },
    { source: "graph-viewer", target: "ext-three", kind: "imports" },
    { source: "graph-viewer", target: "ext-phosphor", kind: "imports" },
    { source: "node-panel", target: "types", kind: "imports" },
    { source: "layer-legend", target: "types", kind: "reads" },
    { source: "analyze-prompt", target: "logo", kind: "imports" },
    { source: "analyze-prompt", target: "settings-store", kind: "imports" },
    { source: "analyze-prompt", target: "ui-terminal", kind: "imports" },

    // preview data
    { source: "previews-index", target: "preview-causalist", kind: "imports" },
    { source: "previews-index", target: "preview-nextjs", kind: "imports" },
    { source: "previews-index", target: "preview-flask", kind: "imports" },
    { source: "preview-causalist", target: "types", kind: "imports" },
    { source: "preview-nextjs", target: "types", kind: "imports" },
    { source: "preview-flask", target: "types", kind: "imports" },
    { source: "devicon", target: "ext-devicon", kind: "calls" },

    // shadcn ui internal
    { source: "ui-button", target: "utils", kind: "imports" },
    { source: "ui-input", target: "utils", kind: "imports" },
    { source: "ui-card", target: "utils", kind: "imports" },
    { source: "ui-dialog", target: "utils", kind: "imports" },
    { source: "ui-sheet", target: "utils", kind: "imports" },
    { source: "ui-command", target: "utils", kind: "imports" },
    { source: "ui-bento", target: "utils", kind: "imports" },
    { source: "ui-beam", target: "utils", kind: "imports" },
    { source: "ui-marquee", target: "utils", kind: "imports" },
    { source: "ui-shiny", target: "utils", kind: "imports" },

    // agent pipeline (conceptual edges)
    { source: "agent-oracle", target: "agent-structure", kind: "reads" },
    { source: "agent-oracle", target: "agent-dependency", kind: "reads" },
    { source: "agent-oracle", target: "agent-semantic", kind: "reads" },
    { source: "agent-structure", target: "ext-anthropic", kind: "calls" },
    { source: "agent-dependency", target: "ext-anthropic", kind: "calls" },
    { source: "agent-semantic", target: "ext-anthropic", kind: "calls" },
    { source: "agent-oracle", target: "ext-anthropic", kind: "calls" },
    { source: "agent-structure", target: "ext-agent-sdk", kind: "calls" },
    { source: "agent-dependency", target: "ext-agent-sdk", kind: "calls" },
    { source: "agent-semantic", target: "ext-agent-sdk", kind: "calls" },
    { source: "agent-oracle", target: "ext-agent-sdk", kind: "calls" },

    // surfaces
    { source: "cli", target: "agent-oracle", kind: "calls" },
    { source: "plugin", target: "cli", kind: "calls" },

    // infra / config
    { source: "pkg", target: "ext-next", kind: "imports" },
    { source: "pkg", target: "ext-react", kind: "imports" },
    { source: "pkg", target: "ext-tailwind", kind: "imports" },
    { source: "pkg", target: "ext-octokit", kind: "imports" },
    { source: "pkg", target: "ext-anthropic", kind: "imports" },
    { source: "pkg", target: "ext-agent-sdk", kind: "imports" },
    { source: "pkg", target: "ext-supabase", kind: "imports" },
    { source: "pkg", target: "ext-framer", kind: "imports" },
    { source: "pkg", target: "ext-phosphor", kind: "imports" },
    { source: "pkg", target: "ext-fg3d", kind: "imports" },
    { source: "pkg", target: "ext-fg2d", kind: "imports" },
    { source: "pkg", target: "ext-three", kind: "imports" },
    { source: "next-config", target: "ext-next", kind: "reads" },
    { source: "tsconfig", target: "ext-next", kind: "reads" },
    { source: "globals", target: "ext-tailwind", kind: "imports" },
    { source: "components-json", target: "utils", kind: "reads" },
  ],
};
