import type { CausalGraph } from "../types";

// Full self-map of daxaur/causalist — every real file in src/ plus the
// packages it depends on. Generated by hand from the current tree. Keep
// this in sync when files move.
export const causalistSelfGraph: CausalGraph = {
  repo: "daxaur/causalist",
  rootLabel: "causalist",
  commit: "main",
  nodes: [
    // ── entry + layout ─────────────────────────────────────────────────
    { id: "layout", label: "app/layout.tsx", path: "src/app/layout.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Root App Router layout wrapping every route. Pulls JetBrains Mono through next/font and a Fontshare <link> for Clash Display + Satoshi, then exposes them as CSS vars the Tailwind theme consumes. Also defines the `metadata` export (title, OG image, applicationName) that drives social previews." },
    { id: "globals", label: "app/globals.css", path: "src/app/globals.css", layer: "config", language: "css", kind: "file", summary: "The single Tailwind v4 entrypoint — `@theme inline` wires --font-display/--font-sans to Clash/Satoshi and declares shadcn's token palette. Also holds the marquee + shiny-text keyframes that Magic UI components animate against." },
    { id: "icon", label: "app/icon.svg", path: "src/app/icon.svg", layer: "ui", language: "svg", kind: "file", summary: "Arc+Terminus favicon discovered by Next's metadata file convention, so `<link rel=icon>` is emitted automatically at 32x32. Edit this and the favicon updates without touching layout.tsx." },
    { id: "og", label: "app/opengraph-image.svg", path: "src/app/opengraph-image.svg", layer: "ui", language: "svg", kind: "file", summary: "Static OpenGraph card picked up by Next's `opengraph-image` file convention. Contains the logo mark plus the Causalist wordmark so Twitter/Slack unfurls show real branding instead of a screenshot." },

    // ── routes ─────────────────────────────────────────────────────────
    { id: "page", label: "app/page.tsx", path: "src/app/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "The marketing landing page. Composes the Clash Display hero, a GitHub URL input that client-validates `owner/repo` before pushing to `/[owner]/[repo]`, a BentoGrid of features, the language marquee, and the Claude credit strip. Uses the constellation canvas as its animated background." },
    { id: "repo-page", label: "app/[owner]/[repo]", path: "src/app/[owner]/[repo]/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "The canonical per-repo route — a server component that awaits `params` (Next 16 makes these async) and decides what to show. If the preview registry has a cached graph it renders <CausalGraphViewer>; otherwise it falls back to <RepoAnalyzePrompt> so the user can trigger an analyze run." },
    { id: "preview-page", label: "app/preview/[slug]", path: "src/app/preview/[slug]/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Static showcase route for the hand-curated demos. `generateStaticParams` enumerates the PREVIEWS registry so `/preview/causalist`, `/preview/nextjs`, and `/preview/flask` are all SSG'd at build time and load instantly." },
    { id: "dashboard-page", label: "app/dashboard", path: "src/app/dashboard/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Authenticated user's repo list. Reads the GitHub PAT from the settings store and paginates the user's repositories through Octokit (`repos.listForAuthenticatedUser`). Each row deep-links to `/[owner]/[repo]` to kick off analysis." },
    { id: "settings-page", label: "app/settings", path: "src/app/settings/page.tsx", layer: "ui", language: "tsx", kind: "file", summary: "BYO-keys screen — inputs for the Anthropic API key and GitHub PAT, each with show/hide toggles. Writes through the settings store (localStorage + useSyncExternalStore) and offers a 'clear' button that wipes both keys." },

    // ── brand / logo ───────────────────────────────────────────────────
    { id: "logo", label: "<Logo>", path: "src/components/brand/logo.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Inline SVG of the Arc+Terminus mark — pure markup, no deps, scales from 16px favicon to full-bleed hero. Also exports <LogoWordmark>, a variant that glues the mark to the Clash Display wordmark for headers." },

    // ── landing background ─────────────────────────────────────────────
    { id: "constellation", label: "<ConstellationBackground>", path: "src/components/landing/constellation-bg.tsx", layer: "ui", language: "tsx", kind: "file", summary: "The animated hero background — a Canvas 2D particle field where dots drift and link to neighbors within a distance threshold, brightening toward the cursor. Runs in a single requestAnimationFrame loop and cleans up on unmount; no three.js involved." },

    // ── graph viewer ───────────────────────────────────────────────────
    { id: "graph-viewer", label: "<CausalGraphViewer>", path: "src/components/graph/causal-graph-viewer.tsx", layer: "ui", language: "tsx", kind: "file", summary: "The centerpiece — renders a CausalGraph via react-force-graph-3d or -2d, dynamically imported with `ssr:false` so three.js never hits the server bundle. Manages the 3D/2D toggle, directional particles colored by edge.kind, node-selection state, and pipes the selected node to <NodePanel>." },
    { id: "node-panel", label: "<NodePanel>", path: "src/components/graph/node-panel.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Right-side drawer that shows the selected node's details. Displays the semantic-layer pill (colored via LAYER_COLORS), the file path, the summary blurb, and kind/language metadata. Receives the node via props from <CausalGraphViewer> and fires an onClose callback to clear selection." },
    { id: "layer-legend", label: "<LayerLegend>", path: "src/components/graph/layer-legend.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Small fixed-position legend at the bottom-left of the viewer. Reads LAYER_COLORS + LAYER_LABELS from types.ts and renders a colored dot per semantic layer so users can decode the graph without clicking." },
    { id: "analyze-prompt", label: "<RepoAnalyzePrompt>", path: "src/components/graph/repo-analyze-prompt.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Fallback UI when a repo has no cached graph yet. Shows the four-stage agent pipeline (Structure → Dependency → Semantic → Oracle) with live progress and embeds <Terminal> for the 'watching Claude think' effect. The Start button is disabled until the settings store reports an Anthropic key." },

    // ── lib: graph data model ──────────────────────────────────────────
    { id: "types", label: "graph/types.ts", path: "src/lib/graph/types.ts", layer: "data", language: "ts", kind: "file", summary: "The shared type contract — `CausalNode`, `CausalEdge`, `CausalGraph`, and the `SemanticLayer` union (ui/logic/data/api/infra/config/test). Also exports LAYER_COLORS and LAYER_LABELS lookup tables that every viewer and legend component reads from." },
    { id: "devicon", label: "graph/devicon.ts", path: "src/lib/graph/devicon.ts", layer: "data", language: "ts", kind: "file", summary: "Translates a node's language or framework tag (ts, py, react, nextjs, etc.) into a devicon jsDelivr URL. The graph viewer uses these URLs to paint a per-node language logo on each sphere/circle." },
    { id: "previews-index", label: "previews/index.ts", path: "src/lib/graph/previews/index.ts", layer: "data", language: "ts", kind: "file", summary: "The preview registry. Imports the three curated graphs, exports them as `PREVIEWS` (array of {slug, graph, ...meta}) plus a `previewBySlug(slug)` helper used by both the preview route and the repo route's cache check." },
    { id: "preview-causalist", label: "previews/causalist.ts", path: "src/lib/graph/previews/causalist.ts", layer: "data", language: "ts", kind: "file", summary: "The recursive self-map you're currently exploring — every file under `src/` plus its external deps encoded as nodes and edges. Lives in the graph it describes as the 'preview-causalist' node, which is why selecting it shows this summary." },
    { id: "preview-nextjs", label: "previews/nextjs.ts", path: "src/lib/graph/previews/nextjs.ts", layer: "data", language: "ts", kind: "file", summary: "Hand-curated slice of vercel/next.js — CLI, build pipeline, server, App Router, rendering primitives, and key externals. Not exhaustive (the real repo has hundreds of packages) but covers the surfaces a developer would want to see." },
    { id: "preview-flask", label: "previews/flask.ts", path: "src/lib/graph/previews/flask.ts", layer: "data", language: "ts", kind: "file", summary: "Near-complete map of pallets/flask's core `flask/` package. Models the sansio base classes, context stack, blueprints, templating/sessions/CLI, and the Werkzeug + Jinja externals everything rests on." },

    // ── lib: settings + analyze ───────────────────────────────────────
    { id: "settings-store", label: "lib/settings.ts", path: "src/lib/settings.ts", layer: "data", language: "ts", kind: "file", summary: "The BYO-keys store. Wraps localStorage behind `useSyncExternalStore` so components re-render when keys change in another tab, and exposes typed getters/setters for the Anthropic key and GitHub PAT. The settings page and analyze-prompt both read through this." },
    { id: "utils", label: "lib/utils.ts", path: "src/lib/utils.ts", layer: "data", language: "ts", kind: "file", summary: "The shadcn `cn()` helper — thin wrapper around `clsx` + `tailwind-merge` that every UI primitive imports to compose conditional Tailwind classes without collisions." },

    // ── config ────────────────────────────────────────────────────────
    { id: "pkg", label: "package.json", path: "package.json", layer: "config", language: "json", kind: "file", summary: "Project manifest pinning the stack: Next 16, React 19, Tailwind v4, three/react-force-graph-3d for the viewer, @anthropic-ai/sdk + @anthropic-ai/claude-agent-sdk for agents, @octokit/rest for GitHub, and @supabase/supabase-js reserved for the phase-2 cache." },
    { id: "tsconfig", label: "tsconfig.json", path: "tsconfig.json", layer: "config", language: "json", kind: "file", summary: "TypeScript config generated by Next — strict mode on, `@/*` path alias mapped to `src/*`, and the `next` plugin wired in for App Router types." },
    { id: "next-config", label: "next.config.ts", path: "next.config.ts", layer: "config", language: "ts", kind: "file", summary: "Minimal Next 16 config — mostly present to pin `turbopack.root` so the dev server stops warning about multiple lockfiles in the monorepo parent. No custom webpack, no experimental flags." },
    { id: "eslint", label: "eslint.config.mjs", path: "eslint.config.mjs", layer: "config", language: "js", kind: "file" },
    { id: "postcss", label: "postcss.config.mjs", path: "postcss.config.mjs", layer: "config", language: "js", kind: "file" },
    { id: "components-json", label: "components.json", path: "components.json", layer: "config", language: "json", kind: "file", summary: "The shadcn/ui CLI manifest. Declares the New York style, the `@/components/ui` output path, and the `utils` alias so `npx shadcn add` scaffolds new primitives straight into this project's conventions." },

    // ── shadcn + magic ui primitives ──────────────────────────────────
    { id: "ui-button", label: "ui/button.tsx", path: "src/components/ui/button.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-input", label: "ui/input.tsx", path: "src/components/ui/input.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-card", label: "ui/card.tsx", path: "src/components/ui/card.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-dialog", label: "ui/dialog.tsx", path: "src/components/ui/dialog.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-sheet", label: "ui/sheet.tsx", path: "src/components/ui/sheet.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-command", label: "ui/command.tsx", path: "src/components/ui/command.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-bento", label: "ui/bento-grid.tsx", path: "src/components/ui/bento-grid.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Magic UI BentoGrid primitives — <BentoGrid> and <BentoCard> — used on the landing page to lay out the features section with hover gradients and icon slots." },
    { id: "ui-beam", label: "ui/animated-beam.tsx", path: "src/components/ui/animated-beam.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Magic UI <AnimatedBeam> — takes two element refs plus a container and draws an animated SVG path between them. The landing page uses it at feature-section scale to re-draw the Arc+Terminus logo motif in-flight." },
    { id: "ui-marquee", label: "ui/marquee.tsx", path: "src/components/ui/marquee.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-ticker", label: "ui/number-ticker.tsx", path: "src/components/ui/number-ticker.tsx", layer: "ui", language: "tsx", kind: "file" },
    { id: "ui-terminal", label: "ui/terminal.tsx", path: "src/components/ui/terminal.tsx", layer: "ui", language: "tsx", kind: "file", summary: "Stylized terminal with a typewriter animation that cycles through lines. Embedded inside <RepoAnalyzePrompt> to give the 'watching Claude think' effect while the agent pipeline runs." },
    { id: "ui-shiny", label: "ui/animated-shiny-text.tsx", path: "src/components/ui/animated-shiny-text.tsx", layer: "ui", language: "tsx", kind: "file" },

    // ── externals ─────────────────────────────────────────────────────
    { id: "ext-next", label: "next", layer: "infra", language: "nextjs", kind: "external", summary: "Next.js 16 App Router. Turbopack dev server." },
    { id: "ext-react", label: "react 19", layer: "infra", language: "react", kind: "external" },
    { id: "ext-tailwind", label: "tailwindcss v4", layer: "infra", language: "tailwindcss", kind: "external" },
    { id: "ext-fg3d", label: "react-force-graph-3d", layer: "infra", language: "react", kind: "external", summary: "Three.js-backed 3D force-directed graph." },
    { id: "ext-fg2d", label: "react-force-graph-2d", layer: "infra", language: "react", kind: "external", summary: "Canvas2D force-directed graph." },
    { id: "ext-three", label: "three", layer: "infra", language: "js", kind: "external" },
    { id: "ext-octokit", label: "@octokit/rest", layer: "infra", language: "github", kind: "external", summary: "GitHub REST client. Used for repo listing + content fetching." },
    { id: "ext-anthropic", label: "@anthropic-ai/sdk", layer: "infra", language: "anthropic", kind: "external", summary: "Claude API client. Oracle agent calls this directly in the browser with user's key." },
    { id: "ext-agent-sdk", label: "@anthropic-ai/claude-agent-sdk", layer: "infra", language: "anthropic", kind: "external", summary: "Subagent orchestrator. Runs Structure/Dependency/Semantic/Oracle in parallel from the Node side." },
    { id: "ext-supabase", label: "@supabase/supabase-js", layer: "data", language: "postgres", kind: "external", summary: "Phase-2 graph cache. Not yet wired." },
    { id: "ext-phosphor", label: "@phosphor-icons/react", layer: "ui", language: "react", kind: "external", summary: "Icon set — duotone for emphasis, regular elsewhere." },
    { id: "ext-framer", label: "framer-motion", layer: "ui", language: "react", kind: "external" },
    { id: "ext-devicon", label: "devicon (CDN)", layer: "ui", language: "html", kind: "external", summary: "Language logos served from jsDelivr." },
    { id: "ext-fontshare", label: "Fontshare", layer: "ui", language: "css", kind: "external", summary: "Hosts Clash Display + Satoshi." },

    // ── agents (conceptual — not yet coded) ────────────────────────────
    { id: "agent-structure", label: "StructureAgent", layer: "logic", language: "anthropic", kind: "module", summary: "Walks file tree, classifies dirs, detects frameworks. System prompt: 'you classify file system nodes.'" },
    { id: "agent-dependency", label: "DependencyAgent", layer: "logic", language: "anthropic", kind: "module", summary: "Extracts import/call/data-flow edges from source via Grep." },
    { id: "agent-semantic", label: "SemanticAgent", layer: "logic", language: "anthropic", kind: "module", summary: "Writes a plain-English summary + layer class for every node." },
    { id: "agent-oracle", label: "OracleAgent", layer: "logic", language: "anthropic", kind: "module", summary: "Merges the three into a final CausalGraph. Handles 'what if?' queries with extended thinking." },

    // ── future surfaces ────────────────────────────────────────────────
    { id: "cli", label: "causalist CLI", layer: "infra", language: "ts", kind: "module", summary: "Node CLI. `causalist map <url>` → JSON → opens browser. Universal — works for any agent with shell access." },
    { id: "plugin", label: "Claude Code plugin", layer: "infra", language: "ts", kind: "module", summary: "Bundle: skill + .mcp.json + bin/causalist. One-line install into Claude Code." },
  ],
  edges: [
    // layout wiring
    { source: "layout", target: "page", kind: "imports" },
    { source: "layout", target: "globals", kind: "imports" },
    { source: "layout", target: "ext-fontshare", kind: "imports" },

    // landing
    { source: "page", target: "constellation", kind: "imports" },
    { source: "page", target: "logo", kind: "imports" },
    { source: "page", target: "ui-button", kind: "imports" },
    { source: "page", target: "ui-input", kind: "imports" },
    { source: "page", target: "ui-bento", kind: "imports" },
    { source: "page", target: "ui-beam", kind: "imports" },
    { source: "page", target: "ui-marquee", kind: "imports" },
    { source: "page", target: "ui-shiny", kind: "imports" },
    { source: "page", target: "settings-store", kind: "imports" },
    { source: "page", target: "ext-phosphor", kind: "imports" },

    // repo page
    { source: "repo-page", target: "logo", kind: "imports" },
    { source: "repo-page", target: "graph-viewer", kind: "imports" },
    { source: "repo-page", target: "analyze-prompt", kind: "imports" },
    { source: "repo-page", target: "previews-index", kind: "imports" },
    { source: "repo-page", target: "ext-phosphor", kind: "imports" },

    // preview page
    { source: "preview-page", target: "logo", kind: "imports" },
    { source: "preview-page", target: "graph-viewer", kind: "imports" },
    { source: "preview-page", target: "previews-index", kind: "imports" },

    // dashboard
    { source: "dashboard-page", target: "logo", kind: "imports" },
    { source: "dashboard-page", target: "settings-store", kind: "imports" },
    { source: "dashboard-page", target: "ext-octokit", kind: "calls" },

    // settings
    { source: "settings-page", target: "logo", kind: "imports" },
    { source: "settings-page", target: "settings-store", kind: "imports" },
    { source: "settings-page", target: "ui-button", kind: "imports" },
    { source: "settings-page", target: "ui-input", kind: "imports" },

    // graph viewer internals
    { source: "graph-viewer", target: "types", kind: "imports" },
    { source: "graph-viewer", target: "devicon", kind: "imports" },
    { source: "graph-viewer", target: "node-panel", kind: "imports" },
    { source: "graph-viewer", target: "layer-legend", kind: "imports" },
    { source: "graph-viewer", target: "ext-fg3d", kind: "imports" },
    { source: "graph-viewer", target: "ext-fg2d", kind: "imports" },
    { source: "graph-viewer", target: "ext-three", kind: "imports" },
    { source: "graph-viewer", target: "ext-phosphor", kind: "imports" },
    { source: "node-panel", target: "types", kind: "imports" },
    { source: "layer-legend", target: "types", kind: "reads" },
    { source: "analyze-prompt", target: "logo", kind: "imports" },
    { source: "analyze-prompt", target: "settings-store", kind: "imports" },
    { source: "analyze-prompt", target: "ui-terminal", kind: "imports" },

    // preview data
    { source: "previews-index", target: "preview-causalist", kind: "imports" },
    { source: "previews-index", target: "preview-nextjs", kind: "imports" },
    { source: "previews-index", target: "preview-flask", kind: "imports" },
    { source: "preview-causalist", target: "types", kind: "imports" },
    { source: "preview-nextjs", target: "types", kind: "imports" },
    { source: "preview-flask", target: "types", kind: "imports" },
    { source: "devicon", target: "ext-devicon", kind: "calls" },

    // shadcn ui internal
    { source: "ui-button", target: "utils", kind: "imports" },
    { source: "ui-input", target: "utils", kind: "imports" },
    { source: "ui-card", target: "utils", kind: "imports" },
    { source: "ui-dialog", target: "utils", kind: "imports" },
    { source: "ui-sheet", target: "utils", kind: "imports" },
    { source: "ui-command", target: "utils", kind: "imports" },
    { source: "ui-bento", target: "utils", kind: "imports" },
    { source: "ui-beam", target: "utils", kind: "imports" },
    { source: "ui-marquee", target: "utils", kind: "imports" },
    { source: "ui-shiny", target: "utils", kind: "imports" },

    // agent pipeline (conceptual edges)
    { source: "agent-oracle", target: "agent-structure", kind: "reads" },
    { source: "agent-oracle", target: "agent-dependency", kind: "reads" },
    { source: "agent-oracle", target: "agent-semantic", kind: "reads" },
    { source: "agent-structure", target: "ext-anthropic", kind: "calls" },
    { source: "agent-dependency", target: "ext-anthropic", kind: "calls" },
    { source: "agent-semantic", target: "ext-anthropic", kind: "calls" },
    { source: "agent-oracle", target: "ext-anthropic", kind: "calls" },
    { source: "agent-structure", target: "ext-agent-sdk", kind: "calls" },
    { source: "agent-dependency", target: "ext-agent-sdk", kind: "calls" },
    { source: "agent-semantic", target: "ext-agent-sdk", kind: "calls" },
    { source: "agent-oracle", target: "ext-agent-sdk", kind: "calls" },

    // surfaces
    { source: "cli", target: "agent-oracle", kind: "calls" },
    { source: "plugin", target: "cli", kind: "calls" },

    // infra / config
    { source: "pkg", target: "ext-next", kind: "imports" },
    { source: "pkg", target: "ext-react", kind: "imports" },
    { source: "pkg", target: "ext-tailwind", kind: "imports" },
    { source: "pkg", target: "ext-octokit", kind: "imports" },
    { source: "pkg", target: "ext-anthropic", kind: "imports" },
    { source: "pkg", target: "ext-agent-sdk", kind: "imports" },
    { source: "pkg", target: "ext-supabase", kind: "imports" },
    { source: "pkg", target: "ext-framer", kind: "imports" },
    { source: "pkg", target: "ext-phosphor", kind: "imports" },
    { source: "pkg", target: "ext-fg3d", kind: "imports" },
    { source: "pkg", target: "ext-fg2d", kind: "imports" },
    { source: "pkg", target: "ext-three", kind: "imports" },
    { source: "next-config", target: "ext-next", kind: "reads" },
    { source: "tsconfig", target: "ext-next", kind: "reads" },
    { source: "globals", target: "ext-tailwind", kind: "imports" },
    { source: "components-json", target: "utils", kind: "reads" },
  ],
};
