import type { CausalGraph } from "../types";

// A small, hand-curated slice of Next.js to show layered architecture.
export const nextjsSliceGraph: CausalGraph = {
  repo: "vercel/next.js",
  rootLabel: "next.js (core slice)",
  commit: "canary",
  nodes: [
    { id: "cli", label: "packages/next/cli", layer: "api", language: "ts", kind: "module", summary: "The `next` CLI entry — dev, build, start, lint." },
    { id: "build", label: "packages/next/build", layer: "logic", language: "ts", kind: "module", summary: "Production build pipeline — Webpack/Turbopack orchestration." },
    { id: "server", label: "packages/next/server", layer: "logic", language: "ts", kind: "module", summary: "HTTP request handling, rendering, routing." },
    { id: "app-router", label: "app-router", layer: "logic", language: "ts", kind: "module", summary: "App Router: RSC, layouts, segments, async params." },
    { id: "pages-router", label: "pages-router", layer: "logic", language: "ts", kind: "module", summary: "Legacy Pages Router." },
    { id: "turbopack", label: "turbopack", layer: "infra", language: "rs", kind: "module", summary: "Rust bundler powering the dev server." },
    { id: "webpack", label: "webpack config", layer: "infra", language: "ts", kind: "module" },
    { id: "client-runtime", label: "client runtime", layer: "ui", language: "tsx", kind: "module", summary: "Hydration, <Link>, <Image>, route prefetch." },
    { id: "nav", label: "navigation APIs", layer: "ui", language: "ts", kind: "module", summary: "useRouter, redirect, useSelectedLayoutSegment." },
    { id: "font", label: "next/font", layer: "ui", language: "ts", kind: "module", summary: "Self-hosted Google + local fonts." },
    { id: "image", label: "next/image", layer: "ui", language: "tsx", kind: "module" },
    { id: "cache", label: "cache layer", layer: "data", language: "ts", kind: "module", summary: "Data cache, request memoization, revalidation." },
    { id: "config", label: "next.config.ts", layer: "config", language: "ts", kind: "file" },
    { id: "test", label: "test/", layer: "test", language: "js", kind: "module" },
    { id: "react", label: "react", layer: "infra", language: "react", kind: "external" },
    { id: "swc", label: "@swc/core", layer: "infra", language: "rs", kind: "external", summary: "Rust-based JS/TS compiler." },
  ],
  edges: [
    { source: "cli", target: "build", kind: "calls" },
    { source: "cli", target: "server", kind: "calls" },
    { source: "build", target: "webpack", kind: "calls" },
    { source: "build", target: "turbopack", kind: "calls" },
    { source: "build", target: "swc", kind: "calls" },
    { source: "server", target: "app-router", kind: "calls" },
    { source: "server", target: "pages-router", kind: "calls" },
    { source: "server", target: "cache", kind: "reads" },
    { source: "app-router", target: "client-runtime", kind: "calls" },
    { source: "app-router", target: "react", kind: "calls" },
    { source: "client-runtime", target: "nav", kind: "imports" },
    { source: "client-runtime", target: "font", kind: "imports" },
    { source: "client-runtime", target: "image", kind: "imports" },
    { source: "config", target: "build", kind: "reads" },
    { source: "config", target: "server", kind: "reads" },
    { source: "test", target: "server", kind: "reads" },
    { source: "test", target: "build", kind: "reads" },
  ],
};
